#!/bin/sh

if [ $(whoami) != "root" ]; then
  echo "Are you sure you want to do this as $(whoami)?"
  echo -n "hit ctrl-c to abort, return to continue"
  read xxx
fi

export PYTHONVER=$(./pydetect -v)
export PYTHONFULLVER=$(./pydetect -vv)
export PYTHONEXE=$(./pydetect -f)
export PYTHONPREFIX=$(./pydetect -p)

export WHO=`/usr/bin/whoami`

if [ "$1" = "-dir" ]; then
  export PYPEDIR=$2
  shift; shift
fi

/usr/bin/make -f Buildfile $*
