#!/bin/sh


\ls ./src/pype/*.py | \
    grep -v gracePlot.py | grep -v grace_np.py | grep -v blt | \
    grep -v PlexHeaders.py | grep -v pstat.py | grep -v stats.py | \
    grep -v mplot.py | grep -v stimlib.py | \
    xargs epydoc --docformat "restructuredtext en" --html \
    --simple-term --parse-only -v --no-private \
    -o ./pypedocs -n pype

ping -c 1 www.mlab.yale.edu >/dev/null
if [ "$?" = "0" ]; then
  echo "mlab: shared doc install"
  /bin/rm -rf /auto/share/pypedocs/*
  cp -rpa pypedocs/* /auto/share/pypedocs
  date > /auto/share/pypedocs/GENERATED
fi

