#!/bin/bash

cd ..
echo "Working in `pwd`..."

#HAPPYDOC="~/Personal/Devel/HappyDoc/happydoc"

if [ "$HAPPYDOC" = "" ]
then
	HAPPYDOC="happydoc"
	VERBOSITY="-q"
else
	VERBOSITY="-vvvv"
fi

echo "HAPPYDOC=$HAPPYDOC"
echo

function make_docs () {
	input_dir="$1" 
	shift 1
	output_dir="$1"
	shift 1
	title="$*"

	echo "Cleaning up old documentation in $output_dir"
	rm -rf $output_dir
	echo "Done"

	echo
	echo "Writing new documentation for $input_dir"
	$HAPPYDOC \
	    $VERBOSITY \
	    -t "$title" \
	    -d "$output_dir" \
	    "$input_dir" 
	echo

    archive_name=${output_dir}.tar.gz
    echo "Archiving to $archive_name..."
    tar zcf $archive_name $output_dir
    echo "Done"
    echo
}


make_docs "Zope-2-CVS-src" "Zope-2-CVS-srcdocs" "Zope2 CVS with ZEO"
#make_docs "Zope-2.3.0-src" "Zope-2.3.0-srcdocs" "Zope 2.3.0"
