#!/usr/bin/env python
#
# Thu Mar 11 13:52:31 2010 mazer 
#
# run matlab and consume header for batch jobs.. command line args
# get passed to matlab as usual..
#

import sys, subprocess

args = sys.argv[:]
args[0] = 'matlab'

proc = subprocess.Popen(args, bufsize=0,
                     stdin=None, stderr=None, stdout=subprocess.PIPE)

holdoutput = 1
while 1:
    l = proc.stdout.readline()
    if len(l) == 0: break
    if holdoutput:
        if l[:3] == '>> ':
            sys.stdout.write(l[3:])
            holdoutput = 0
    else:
        sys.stdout.write(l)
