#!/bin/sh

sed "s/%%INSTALLDATE%%/`date`/g" <<EOF
# -*- Mode: Python; tab-width: 4; py-indent-offset: 4; -*-
# $Id: pypeversion.py.template 312 2009-03-31 19:57:23Z mazer $

"""Version and compilation info.

Autogenerated file -- **DO NOT USE DIRECTLY**

This file is automatically generated during the build process. Changes
will be lost on the next build.
"""

PypeVersion = "2.0"
PypeInstallDate = "%%INSTALLDATE%%"
EOF

echo "PypeBuildDir = \"`pwd`\""
echo "PypeBuildBy = \"$LOGNAME\""
echo "PypeBuildDate = \"`date`\""
echo "PypeBuildHost = \"`hostname`\""

if [ -e /usr/bin/svn ]; then
  echo 'PypeSvnInfo = """'
  svn info
  echo '"""'
  echo -n 'PypeSvnRev = '; svn info | grep ^Revision: | awk '{print $2}'
else
  echo 'PypeSvnInfo = ""'
  echo 'PypeSvnRev = -1'
fi



