#!/bin/sh

# kill stray pype processes -- AS ROOT!! BE CAREFULL

ps -Al --width=1000 2>/dev/null | \
    egrep "(pyperun|das.*server|iscan_server|comedi_server|dummy_server)" | \
	grep -v grep | tee /dev/tty | \
	awk '{print $4}' | xargs -r pypeboot kill -9

# free up semaphores
ipcs -s | grep ^0x | awk '{print $2}' | \
	xargs -r pypeboot ipcrm sem > /dev/null

# free up shared memory segments
ipcs -m | grep ^0x | awk '{print $2}' | \
	xargs -r pypeboot ipcrm shm >/dev/null
